### ISSUE TITLE
Building wheel for scipy (setup.py) ... error while installing on Windows 10

### ISSUE THREAD

**Issue by Moosebaby** [ijmarshall/robotsearch#2]
I tried to install robotsearch as instructions, that is
> Install RobotSearch using the following command (easiest to copy/paste): pip install -U https://github.com/ijmarshall/robotsearch/archive/master.zip
I got the following error:
```
Building wheel for robotsearch (setup.py) ... done
  Stored in directory: C:\Users\47613\AppData\Local\Temp\pip-ephem-wheel-cache-yac4gqe9\wheels\a8\b5\4e\2a1cf35db5ff9bbfa1a4f0a37563ccfe7ae5fd823e79338f77
  Building wheel for scipy (setup.py) ... error
  ERROR: Complete output from command 'c:\program files\python36\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\47613\\AppData\\Local\\Temp\\pip-install-fs3i2e1g\\scipy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\47613\AppData\Local\Temp\pip-wheel-b95umijv' --python-tag cp36:
  ERROR: lapack_opt_info:
  lapack_mkl_info:
  c:\program files\python36\lib\site-packages\numpy\distutils\system_info.py:708: UserWarning: Specified path C:/Program Files (x86)/IntelSWTools/compilers_and_libraries_2019/windows/mkl/lib/intel64_win is invalid.
    return self.get_paths(self.section, key)
  c:\program files\python36\lib\site-packages\numpy\distutils\system_info.py:708: UserWarning: Specified path C:/Program Files (x86)/IntelSWTools/compilers_and_libraries_2019/windows/compiler/lib/intel64_win is invalid.
    return self.get_paths(self.section, key)
  c:\program files\python36\lib\site-packages\numpy\distutils\system_info.py:719: UserWarning: Specified path C:/Program Files (x86)/IntelSWTools/compilers_and_libraries_2019/windows/mkl/include is invalid.
    return self.get_paths(self.section, key)
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries mkl_lapack95_lp64,mkl_blas95_lp64,mkl_rt not found in []
    NOT AVAILABLE

  openblas_lapack_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries openblas not found in ['c:\\program files\\python36\\lib', 'C:\\', 'c:\\program files\\python36\\libs']
  get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
  customize GnuFCompiler
  Could not locate executable g77
  Could not locate executable f77
  customize IntelVisualFCompiler
  Could not locate executable ifort
  Could not locate executable ifl
  customize AbsoftFCompiler
  Could not locate executable f90
  customize CompaqVisualFCompiler
  Could not locate executable DF
  customize IntelItaniumVisualFCompiler
  Could not locate executable efl
  customize Gnu95FCompiler
  Found executable C:\MinGW\bin\gfortran.exe
    NOT AVAILABLE

  openblas_clapack_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries openblas,lapack not found in ['c:\\program files\\python36\\lib', 'C:\\', 'c:\\program files\\python36\\libs']
  get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
  customize GnuFCompiler
  customize IntelVisualFCompiler
  customize AbsoftFCompiler
  customize CompaqVisualFCompiler
  customize IntelItaniumVisualFCompiler
  customize Gnu95FCompiler
    NOT AVAILABLE

  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries tatlas,tatlas not found in c:\program files\python36\lib
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in c:\program files\python36\lib
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries tatlas,tatlas not found in C:\
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries tatlas,tatlas not found in c:\program files\python36\libs
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in c:\program files\python36\libs
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE

  atlas_3_10_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries satlas,satlas not found in c:\program files\python36\lib
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in c:\program files\python36\lib
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries satlas,satlas not found in C:\
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries satlas,satlas not found in c:\program files\python36\libs
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in c:\program files\python36\libs
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE

  atlas_threads_info:
  Setting PTATLAS=ATLAS
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries ptf77blas,ptcblas,atlas not found in c:\program files\python36\lib
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in c:\program files\python36\lib
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries ptf77blas,ptcblas,atlas not found in C:\
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries ptf77blas,ptcblas,atlas not found in c:\program files\python36\libs
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in c:\program files\python36\libs
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE

  atlas_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries f77blas,cblas,atlas not found in c:\program files\python36\lib
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in c:\program files\python36\lib
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries f77blas,cblas,atlas not found in C:\
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in C:\
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries f77blas,cblas,atlas not found in c:\program files\python36\libs
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack_atlas not found in c:\program files\python36\libs
  <class 'numpy.distutils.system_info.atlas_info'>
    NOT AVAILABLE

  accelerate_info:
    NOT AVAILABLE

  c:\program files\python36\lib\site-packages\numpy\distutils\system_info.py:625: UserWarning:
      Atlas (http://math-atlas.sourceforge.net/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [atlas]) or by setting
      the ATLAS environment variable.
    self.calc_info()
  lapack_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries lapack not found in ['c:\\program files\\python36\\lib', 'C:\\', 'c:\\program files\\python36\\libs']
    NOT AVAILABLE

  c:\program files\python36\lib\site-packages\numpy\distutils\system_info.py:625: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    self.calc_info()
  lapack_src_info:
    NOT AVAILABLE

  c:\program files\python36\lib\site-packages\numpy\distutils\system_info.py:625: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    self.calc_info()
    NOT AVAILABLE

  Running from scipy source directory.
  non-existing path in 'scipy\\integrate': 'quadpack.h'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\47613\AppData\Local\Temp\pip-install-fs3i2e1g\scipy\setup.py", line 416, in <module>
      setup_package()
    File "C:\Users\47613\AppData\Local\Temp\pip-install-fs3i2e1g\scipy\setup.py", line 412, in setup_package
      setup(**metadata)
    File "c:\program files\python36\lib\site-packages\numpy\distutils\core.py", line 135, in setup
      config = configuration()
    File "C:\Users\47613\AppData\Local\Temp\pip-install-fs3i2e1g\scipy\setup.py", line 336, in configuration
      config.add_subpackage('scipy')
    File "c:\program files\python36\lib\site-packages\numpy\distutils\misc_util.py", line 1037, in add_subpackage
      caller_level = 2)
    File "c:\program files\python36\lib\site-packages\numpy\distutils\misc_util.py", line 1006, in get_subpackage
      caller_level = caller_level + 1)
    File "c:\program files\python36\lib\site-packages\numpy\distutils\misc_util.py", line 943, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\setup.py", line 15, in configuration
      config.add_subpackage('linalg')
    File "c:\program files\python36\lib\site-packages\numpy\distutils\misc_util.py", line 1037, in add_subpackage
      caller_level = 2)
    File "c:\program files\python36\lib\site-packages\numpy\distutils\misc_util.py", line 1006, in get_subpackage
      caller_level = caller_level + 1)
    File "c:\program files\python36\lib\site-packages\numpy\distutils\misc_util.py", line 943, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\linalg\setup.py", line 20, in configuration
      raise NotFoundError('no lapack/blas resources found')
  numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
  ----------------------------------------
  ERROR: Failed building wheel for scipy
  Running setup.py clean for scipy
  ERROR: Complete output from command 'c:\program files\python36\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\47613\\AppData\\Local\\Temp\\pip-install-fs3i2e1g\\scipy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all:
  ERROR:
  `setup.py clean` is not supported, use one of the following instead:

    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)

  Add `--force` to your command to use it anyway if you must (unsupported).

  ----------------------------------------
  ERROR: Failed cleaning build dir for scipy
Successfully built robotsearch
Failed to build scipy
Installing collected packages: scipy, numpy, tensorflow-tensorboard, tensorflow, scikit-learn, theano, pyyaml, Keras, h5py, robotsearch
  Found existing installation: scipy 1.3.0
    Uninstalling scipy-1.3.0:
      Successfully uninstalled scipy-1.3.0
  Running setup.py install for scipy ... error
    ERROR: Complete output from command 'c:\program files\python36\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\47613\\AppData\\Local\\Temp\\pip-install-fs3i2e1g\\scipy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\47613\AppData\Local\Temp\pip-record-4qrbc9t8\install-record.txt' --single-version-externally-managed --compile:
    ERROR:
    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:

      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)


    lapack_opt_info:
    lapack_mkl_info:
    c:\program files\python36\lib\site-packages\numpy\distutils\system_info.py:708: UserWarning: Specified path C:/Program Files (x86)/IntelSWTools/compilers_and_libraries_2019/windows/mkl/lib/intel64_win is invalid.
      return self.get_paths(self.section, key)
    c:\program files\python36\lib\site-packages\numpy\distutils\system_info.py:708: UserWarning: Specified path C:/Program Files (x86)/IntelSWTools/compilers_and_libraries_2019/windows/compiler/lib/intel64_win is invalid.
      return self.get_paths(self.section, key)
    c:\program files\python36\lib\site-packages\numpy\distutils\system_info.py:719: UserWarning: Specified path C:/Program Files (x86)/IntelSWTools/compilers_and_libraries_2019/windows/mkl/include is invalid.
      return self.get_paths(self.section, key)
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries mkl_lapack95_lp64,mkl_blas95_lp64,mkl_rt not found in []
      NOT AVAILABLE

    openblas_lapack_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries openblas not found in ['c:\\program files\\python36\\lib', 'C:\\', 'c:\\program files\\python36\\libs']
    get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
    customize GnuFCompiler
    Could not locate executable g77
    Could not locate executable f77
    customize IntelVisualFCompiler
    Could not locate executable ifort
    Could not locate executable ifl
    customize AbsoftFCompiler
    Could not locate executable f90
    customize CompaqVisualFCompiler
    Could not locate executable DF
    customize IntelItaniumVisualFCompiler
    Could not locate executable efl
    customize Gnu95FCompiler
    Found executable C:\MinGW\bin\gfortran.exe
      NOT AVAILABLE

    openblas_clapack_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries openblas,lapack not found in ['c:\\program files\\python36\\lib', 'C:\\', 'c:\\program files\\python36\\libs']
    get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
    customize GnuFCompiler
    customize IntelVisualFCompiler
    customize AbsoftFCompiler
    customize CompaqVisualFCompiler
    customize IntelItaniumVisualFCompiler
    customize Gnu95FCompiler
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries tatlas,tatlas not found in c:\program files\python36\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\program files\python36\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries tatlas,tatlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries tatlas,tatlas not found in c:\program files\python36\libs
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\program files\python36\libs
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries satlas,satlas not found in c:\program files\python36\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\program files\python36\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries satlas,satlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries satlas,satlas not found in c:\program files\python36\libs
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\program files\python36\libs
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries ptf77blas,ptcblas,atlas not found in c:\program files\python36\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\program files\python36\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries ptf77blas,ptcblas,atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries ptf77blas,ptcblas,atlas not found in c:\program files\python36\libs
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\program files\python36\libs
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries f77blas,cblas,atlas not found in c:\program files\python36\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\program files\python36\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries f77blas,cblas,atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries f77blas,cblas,atlas not found in c:\program files\python36\libs
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\program files\python36\libs
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    accelerate_info:
      NOT AVAILABLE

    c:\program files\python36\lib\site-packages\numpy\distutils\system_info.py:625: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    lapack_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack not found in ['c:\\program files\\python36\\lib', 'C:\\', 'c:\\program files\\python36\\libs']
      NOT AVAILABLE

    c:\program files\python36\lib\site-packages\numpy\distutils\system_info.py:625: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    lapack_src_info:
      NOT AVAILABLE

    c:\program files\python36\lib\site-packages\numpy\distutils\system_info.py:625: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
      NOT AVAILABLE

    Running from scipy source directory.
    non-existing path in 'scipy\\integrate': 'quadpack.h'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\47613\AppData\Local\Temp\pip-install-fs3i2e1g\scipy\setup.py", line 416, in <module>
        setup_package()
      File "C:\Users\47613\AppData\Local\Temp\pip-install-fs3i2e1g\scipy\setup.py", line 412, in setup_package
        setup(**metadata)
      File "c:\program files\python36\lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "C:\Users\47613\AppData\Local\Temp\pip-install-fs3i2e1g\scipy\setup.py", line 336, in configuration
        config.add_subpackage('scipy')
      File "c:\program files\python36\lib\site-packages\numpy\distutils\misc_util.py", line 1037, in add_subpackage
        caller_level = 2)
      File "c:\program files\python36\lib\site-packages\numpy\distutils\misc_util.py", line 1006, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\program files\python36\lib\site-packages\numpy\distutils\misc_util.py", line 943, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "c:\program files\python36\lib\site-packages\numpy\distutils\misc_util.py", line 1037, in add_subpackage
        caller_level = 2)
      File "c:\program files\python36\lib\site-packages\numpy\distutils\misc_util.py", line 1006, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\program files\python36\lib\site-packages\numpy\distutils\misc_util.py", line 943, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\linalg\setup.py", line 20, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
    ----------------------------------------
  Rolling back uninstall of scipy
  Moving to c:\program files\python36\lib\site-packages\scipy-1.3.0.dist-info\
   from c:\program files\python36\lib\site-packages\~cipy-1.3.0.dist-info
  Moving to c:\program files\python36\lib\site-packages\scipy\
   from c:\program files\python36\lib\site-packages\~cipy
ERROR: Command "'c:\program files\python36\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\47613\\AppData\\Local\\Temp\\pip-install-fs3i2e1g\\scipy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\47613\AppData\Local\Temp\pip-record-4qrbc9t8\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\47613\AppData\Local\Temp\pip-install-fs3i2e1g\scipy\
```
I tried to install scipy manually from https://www.lfd.uci.edu/~gohlke/pythonlibs/, but the above error still occured.

**Comment by Moosebaby** [comment]
I solved this problem. 
1. Direct to the project folder. Edit the setup.py file, change install requires to following: 
`install_requires = ['scipy==1.4.1',
					'numpy==1.18.4',
					'tensorflow==1.5.0',
					'scikit_learn==0.19.1',
					'Keras==2.1.3',
					'h5py==2.7.1']
`

2, Use 'python setup.py install' to install the robotsearch module


3. Edit classfier.py at line 48
`with np.load(filename, encoding='latin1',allow_pickle=True) as raw_data: // set allow_pickle to True`
There you go.

**Comment by ghost** [comment]
But in general case, if I'm not installing the packages for a specific project, I am installing them globally, to be available to all projects. Where can I find the setup.py?

**Comment by tarensanders** [comment]
For anyone else struggling to install, I had success with:

1. `conda env create -f rs_env.yml` & `conda activate robotsearch`
2. Edit 'setup.py' to use the versions that match the YAML file. I.e., 
```
install_requires = ['scipy==1.5.2',
                               'numpy==1.16.1',
                               'tensorflow==1.5.0',
                               'scikit_learn==0.23.2',
                               'keras==2.1.5',
                               'h5py==2.7.1']
```
3. `python setup.py install`
4. Use `robotsearch [path to file]` etc as usual.

I didn't need to edit classifier.py like those above.
